# Generated by Django 4.1.2 on 2022-10-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_key', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('depth', models.IntegerField()),
                ('ancestor', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
